# -*- coding: utf-8 -*-
"""Beschreibungen der mehrstufigen Rechenaufgaben.

Eine Komplexaufgabe ist nicht "schwerer", weil die Zahlen groesser sind,
sondern weil zwischen Angabe und Ergebnis mehrere Schritte liegen, die die
Aufgabe nicht nennt. Bei der Hauptzeit am Drehteil steht die
Vorschubgeschwindigkeit nirgends - sie entsteht erst aus Drehzahl und
Vorschub, und die Drehzahl erst aus Schnittgeschwindigkeit und Durchmesser.
Genau diese Kette ist der Lernstoff.

Jeder Eintrag beschreibt die Aufgabe EINMAL. Fragetext, Loesungswert,
Erklaerung und Loesungsweg fuer den Bestand rechnet tool/komplex_setzen.py
daraus aus - mit denselben Formeln, aus denen spaeter gewuerfelt wird. So
koennen gespeicherter Wert und Variantenformel gar nicht auseinanderlaufen.

Felder je Aufgabe:
  bereich, kategorie   ordnen sie in Lernstand und Auswertungen ein
  variablen            was gewuerfelt wird (siehe docs/FRAGENFORMAT.md)
  original             die Werte, mit denen die Aufgabe im Bestand steht
  zwischen             Zwischenschritte, der Reihe nach ausgewertet
  loesung              Formel fuer das Endergebnis
  rundung              Nachkommastellen des Ergebnisses
  toleranzProzent      Toleranz, skaliert mit dem Ergebnis
  stellen              feste Nachkommastellen einzelner Groessen
"""

AUFGABEN = [
    # ------------------------------------------------------------------
    # Aus dem Bestand weitergedacht: Schnittdaten enden dort bei der
    # Drehzahl. Hier geht es bis zur Zeit, die das Teil wirklich kostet.
    # ------------------------------------------------------------------
    {
        "id": "kx-01",
        "bereich": "fertigungstechnik",
        "kategorie": "Schnittdaten",
        "einheit": "min",
        "rundung": 2,
        "toleranzProzent": 2.0,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"werte": [40, 50, 60, 80, 100]},
            "vc": {"von": 120, "bis": 260, "schritt": 10},
            "f": {"werte": [0.15, 0.2, 0.25, 0.3]},
            "L": {"von": 60, "bis": 250, "schritt": 10},
            "zugabe": {"werte": [4, 5, 6, 8]},
        },
        "original": {"d": 60, "vc": 180, "f": 0.25, "L": 120, "zugabe": 5},
        "zwischen": [
            ("n", "round(vc * 1000 / (pi * d) * 10) / 10"),
            ("vf", "round(vc * 1000 / (pi * d) * f * 10) / 10"),
            ("weg", "L + zugabe"),
        ],
        "loesung": "(L + zugabe) / (vc * 1000 / (pi * d) * f)",
        "frage": "An einer Drehmaschine wird ein Bolzen mit Ø {d} mm über eine Länge von {L} mm längsgedreht. Die Schnittgeschwindigkeit beträgt vc = {vc} m/min, der Vorschub f = {f} mm/U. Für An- und Überlauf sind {zugabe} mm zusätzlich einzuplanen. Wie groß ist die Hauptzeit th (in min)?",
        "erklaerung": "Die Hauptzeit folgt aus Weg und Vorschubgeschwindigkeit – aber vf steht nicht in der Aufgabe. Zugänglich wird sie erst über die Drehzahl: n = vc · 1000 / (π · d), dann vf = n · f. An- und Überlauf gehören zum Weg, denn das Werkzeug muss vor dem Werkstück anlaufen und hinter ihm austreten.",
        "workedExample": "Gegeben: d = {d} mm, L = {L} mm, vc = {vc} m/min, f = {f} mm/U, An-/Überlauf {zugabe} mm\nGesucht: Hauptzeit th\nSchritt 1 – Drehzahl: n = vc · 1000 / (π · d) = {vc} · 1000 / (π · {d}) ≈ {n} 1/min\nSchritt 2 – Vorschubgeschwindigkeit: vf = n · f = {n} · {f} ≈ {vf} mm/min\nSchritt 3 – Weg: L_ges = {L} + {zugabe} = {weg} mm\nSchritt 4 – Hauptzeit: th = L_ges / vf = {weg} / {vf} ≈ {loesung} min",
    },
    {
        "id": "kx-02",
        "bereich": "fertigungstechnik",
        "kategorie": "Schnittdaten",
        "einheit": "min",
        "rundung": 2,
        "toleranzProzent": 2.0,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"werte": [50, 63, 80, 100, 125]},
            "z": {"werte": [4, 5, 6, 8, 10]},
            "vc": {"von": 80, "bis": 200, "schritt": 10},
            "fz": {"werte": [0.08, 0.1, 0.12, 0.15, 0.2]},
            "L": {"von": 150, "bis": 400, "schritt": 10},
            "zugabe": {"werte": [60, 70, 80, 90]},
        },
        "original": {"d": 80, "z": 6, "vc": 120, "fz": 0.12, "L": 250, "zugabe": 80},
        "zwischen": [
            ("n", "round(vc * 1000 / (pi * d) * 10) / 10"),
            ("vf", "round(vc * 1000 / (pi * d) * z * fz * 10) / 10"),
            ("weg", "L + zugabe"),
        ],
        "loesung": "(L + zugabe) / (vc * 1000 / (pi * d) * z * fz)",
        "frage": "Eine Fläche von {L} mm Länge wird mit einem Walzenstirnfräser Ø {d} mm mit {z} Schneiden bearbeitet. Vorgegeben sind vc = {vc} m/min und ein Zahnvorschub fz = {fz} mm. An- und Überlauf betragen zusammen {zugabe} mm. Wie groß ist die Hauptzeit th (in min)?",
        "erklaerung": "Beim Fräsen hängt der Vorschub an der Zähnezahl: vf = n · z · fz. Wer fz mit f verwechselt, rechnet um den Faktor z daneben. Die Drehzahl kommt wie beim Drehen aus n = vc · 1000 / (π · d) – der Durchmesser ist hier der des Werkzeugs, nicht des Werkstücks.",
        "workedExample": "Gegeben: d = {d} mm, z = {z}, vc = {vc} m/min, fz = {fz} mm, L = {L} mm, An-/Überlauf {zugabe} mm\nGesucht: Hauptzeit th\nSchritt 1 – Drehzahl: n = vc · 1000 / (π · d) ≈ {n} 1/min\nSchritt 2 – Vorschubgeschwindigkeit: vf = n · z · fz = {n} · {z} · {fz} ≈ {vf} mm/min\nSchritt 3 – Weg: L_ges = {L} + {zugabe} = {weg} mm\nSchritt 4 – Hauptzeit: th = {weg} / {vf} ≈ {loesung} min",
    },
    {
        "id": "kx-03",
        "bereich": "auftragsanalyse",
        "kategorie": "Antriebstechnik (mechanisch)",
        "einheit": "N·m",
        "rundung": 2,
        "toleranzProzent": 1.5,
        "schwierigkeit": 3,
        "variablen": {
            "P": {"werte": [3.0, 4.0, 5.5, 7.5, 11.0, 15.0]},
            "n1": {"werte": [730, 960, 1450, 2900]},
            "z1": {"werte": [14, 16, 18, 20]},
            "z2": {"werte": [42, 48, 54, 60]},
            "z3": {"werte": [16, 18, 20, 22]},
            "z4": {"werte": [54, 60, 66, 72]},
            "eta": {"werte": [0.95, 0.96, 0.97, 0.98]},
        },
        "original": {
            "P": 7.5, "n1": 1450, "z1": 16, "z2": 48,
            "z3": 20, "z4": 60, "eta": 0.97,
        },
        "zwischen": [
            ("i1", "round(z2 / z1 * 1000) / 1000"),
            ("i2", "round(z4 / z3 * 1000) / 1000"),
            ("i_ges", "round(z2 / z1 * z4 / z3 * 1000) / 1000"),
            ("n_ab", "round(n1 / (z2 / z1 * z4 / z3) * 100) / 100"),
            ("eta_ges", "round(eta^2 * 10000) / 10000"),
        ],
        "loesung": "9550 * P * eta^2 / (n1 / (z2 / z1 * z4 / z3))",
        "frage": "Ein Motor mit P = {P} kW und n₁ = {n1} min⁻¹ treibt ein zweistufiges Stirnradgetriebe an. Stufe 1: z₁ = {z1} auf z₂ = {z2}. Stufe 2: z₃ = {z3} auf z₄ = {z4}. Jede Stufe hat den Wirkungsgrad η = {eta}. Welches Drehmoment M (in N·m) steht an der Abtriebswelle zur Verfügung?",
        "erklaerung": "Drei Ketten greifen ineinander: Die Übersetzungen multiplizieren sich (i_ges = i₁ · i₂), die Wirkungsgrade ebenfalls (η_ges = η²), und erst mit der Abtriebsdrehzahl lässt sich M = 9550 · P · η_ges / n_ab bilden. Ein häufiger Fehler ist, die Übersetzungen zu addieren oder den Wirkungsgrad nur einmal anzusetzen.",
        "workedExample": "Gegeben: P = {P} kW, n₁ = {n1} min⁻¹, z₁/z₂ = {z1}/{z2}, z₃/z₄ = {z3}/{z4}, η = {eta} je Stufe\nGesucht: Abtriebsdrehmoment M\nSchritt 1 – Einzelübersetzungen: i₁ = {z2}/{z1} = {i1}, i₂ = {z4}/{z3} = {i2}\nSchritt 2 – Gesamtübersetzung: i_ges = i₁ · i₂ = {i_ges}\nSchritt 3 – Abtriebsdrehzahl: n_ab = n₁ / i_ges = {n1} / {i_ges} ≈ {n_ab} min⁻¹\nSchritt 4 – Gesamtwirkungsgrad: η_ges = {eta}² = {eta_ges}\nSchritt 5 – Drehmoment: M = 9550 · P · η_ges / n_ab = 9550 · {P} · {eta_ges} / {n_ab} ≈ {loesung} N·m",
    },
    {
        "id": "kx-04",
        "bereich": "auftragsanalyse",
        "kategorie": "Hydraulik",
        "einheit": "s",
        "rundung": 2,
        "toleranzProzent": 1.5,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"werte": [63, 80, 100, 125, 160]},
            "verh": {"werte": [0.4, 0.45, 0.5, 0.56, 0.6]},
            "s": {"von": 100, "bis": 800, "schritt": 50},
            "Q": {"von": 10, "bis": 60, "schritt": 5},
        },
        "original": {"d": 100, "verh": 0.56, "s": 400, "Q": 25},
        "zwischen": [
            ("ds", "round(d * verh)"),
            ("A_k", "round(pi / 4 * d^2 * 100) / 100"),
            ("A_r", "round(pi / 4 * (d^2 - round(d * verh)^2) * 100) / 100"),
            ("V_ges", "round((pi / 4 * d^2 + pi / 4 * (d^2 - round(d * verh)^2)) * s)"),
            ("Q_s", "round(Q * 1000000 / 60)"),
        ],
        "loesung": "(pi / 4 * d^2 + pi / 4 * (d^2 - round(d * verh)^2)) * s / (Q * 1000000 / 60)",
        "frage": "Ein doppeltwirkender Hydraulikzylinder hat einen Kolbendurchmesser von Ø {d} mm, eine Kolbenstange von Ø {ds} mm und einen Hub von {s} mm. Die Pumpe fördert konstant Q = {Q} L/min. Wie lange dauert ein vollständiger Doppelhub (Ausfahren und Einfahren) in Sekunden?",
        "erklaerung": "Der Zylinder ist in beide Richtungen unterschiedlich schnell: Beim Ausfahren wirkt die volle Kolbenfläche, beim Einfahren nur die Ringfläche, weil die Kolbenstange Platz wegnimmt. Bei gleichem Volumenstrom fährt er deshalb schneller ein als aus. Für den Doppelhub addiert man die beiden Volumina und teilt durch den Volumenstrom – auf eine einheitliche Einheit umgerechnet.",
        "workedExample": "Gegeben: d = {d} mm, dₛ = {ds} mm, s = {s} mm, Q = {Q} L/min\nGesucht: Zeit für einen Doppelhub\nSchritt 1 – Kolbenfläche: A_K = π/4 · {d}² ≈ {A_k} mm²\nSchritt 2 – Ringfläche: A_R = π/4 · ({d}² − {ds}²) ≈ {A_r} mm²\nSchritt 3 – Volumen je Doppelhub: V = (A_K + A_R) · s ≈ {V_ges} mm³\nSchritt 4 – Volumenstrom umrechnen: Q = {Q} L/min = {Q_s} mm³/s\nSchritt 5 – Zeit: t = V / Q = {V_ges} / {Q_s} ≈ {loesung} s",
    },
    {
        "id": "kx-05",
        "bereich": "auftragsanalyse",
        "kategorie": "Hydraulik",
        "einheit": "N",
        "rundung": 0,
        "toleranzProzent": 1.5,
        "schwierigkeit": 3,
        "variablen": {
            "A1": {"werte": [8, 10, 12, 16, 20]},
            "F1": {"von": 200, "bis": 1500, "schritt": 50},
            "A2": {"werte": [60, 80, 90, 110, 130]},
            "eta": {"werte": [0.85, 0.88, 0.9, 0.92]},
        },
        "original": {"A1": 12, "F1": 800, "A2": 90, "eta": 0.9},
        "zwischen": [
            ("p_ncm", "round(F1 / A1 * 100) / 100"),
            ("p_bar", "round(F1 / A1 / 10 * 100) / 100"),
            ("F_ideal", "round(F1 / A1 * A2)"),
        ],
        "loesung": "F1 / A1 * A2 * eta",
        "frage": "In einer hydraulischen Presse wirkt auf den kleinen Kolben (A₁ = {A1} cm²) eine Kraft von F₁ = {F1} N. Der große Kolben hat A₂ = {A2} cm². Der Wirkungsgrad der Anlage beträgt η = {eta}. Welche Kraft F₂ (in N) steht am großen Kolben zur Verfügung?",
        "erklaerung": "Nach Pascal ist der Druck im ruhenden Fluid überall gleich – er ist das Bindeglied zwischen den beiden Kolben. Erst über p = F₁/A₁ lässt sich F₂ = p · A₂ bilden. Der Wirkungsgrad kommt zuletzt und verkleinert das Ergebnis; wer ihn im Zähler ansetzt, bekommt mehr Kraft heraus, als hineingesteckt wurde.",
        "workedExample": "Gegeben: A₁ = {A1} cm², F₁ = {F1} N, A₂ = {A2} cm², η = {eta}\nGesucht: F₂\nSchritt 1 – Druck: p = F₁ / A₁ = {F1} / {A1} ≈ {p_ncm} N/cm² ≈ {p_bar} bar\nSchritt 2 – Kraft ohne Verluste: F₂,ideal = p · A₂ = {p_ncm} · {A2} ≈ {F_ideal} N\nSchritt 3 – Wirkungsgrad: F₂ = F₂,ideal · η = {F_ideal} · {eta} ≈ {loesung} N",
    },
    {
        "id": "kx-06",
        "bereich": "auftragsanalyse",
        "kategorie": "Elektrotechnik & Sensorik",
        "einheit": "A",
        "rundung": 2,
        "toleranzProzent": 1.5,
        "schwierigkeit": 3,
        "variablen": {
            "P": {"werte": [3.0, 4.0, 5.5, 7.5, 11.0, 15.0, 18.5, 22.0]},
            "eta": {"werte": [0.85, 0.88, 0.9, 0.91, 0.93]},
            "cosphi": {"werte": [0.8, 0.82, 0.85, 0.86, 0.88]},
            "U": {"werte": [400]},
        },
        "original": {"P": 11.0, "eta": 0.91, "cosphi": 0.86, "U": 400},
        "zwischen": [
            ("P_zu", "round(P * 1000 / eta * 10) / 10"),
            ("nenner", "round(sqrt(3) * U * cosphi * 100) / 100"),
        ],
        "loesung": "P * 1000 / eta / (sqrt(3) * U * cosphi)",
        "frage": "Ein Drehstrommotor gibt an der Welle P = {P} kW ab. Sein Wirkungsgrad beträgt η = {eta}, der Leistungsfaktor cos φ = {cosphi}, die Netzspannung U = {U} V. Welchen Strom I (in A) nimmt der Motor auf?",
        "erklaerung": "Zwei Fallen stecken darin. Erstens ist die Typenschildleistung die ABGEGEBENE Leistung – aufgenommen wird mehr, nämlich P/η. Zweitens gilt bei Drehstrom P = √3 · U · I · cos φ; wer den Faktor √3 vergisst, landet um 73 % zu hoch.",
        "workedExample": "Gegeben: P_ab = {P} kW, η = {eta}, cos φ = {cosphi}, U = {U} V\nGesucht: Aufgenommener Strom I\nSchritt 1 – Aufgenommene Leistung: P_zu = P_ab / η = {P} · 1000 / {eta} ≈ {P_zu} W\nSchritt 2 – Nenner bilden: √3 · U · cos φ = 1,7321 · {U} · {cosphi} ≈ {nenner}\nSchritt 3 – Strom: I = P_zu / (√3 · U · cos φ) = {P_zu} / {nenner} ≈ {loesung} A",
    },
    {
        "id": "kx-07",
        "bereich": "auftragsanalyse",
        "kategorie": "Technische Berechnungen",
        "einheit": "MJ",
        "rundung": 2,
        "toleranzProzent": 1.0,
        "schwierigkeit": 3,
        "variablen": {
            "m": {"von": 5, "bis": 60, "schritt": 5},
            "T1": {"von": 15, "bis": 40, "schritt": 5},
            "c": {"werte": [0.9]},
            "q": {"werte": [397]},
            "T2": {"werte": [660]},
        },
        "original": {"m": 25, "T1": 20, "c": 0.9, "q": 397, "T2": 660},
        "zwischen": [
            ("dT", "T2 - T1"),
            ("Q1", "round(m * c * (T2 - T1))"),
            ("Q2", "round(m * q)"),
            ("Q_kJ", "round(m * c * (T2 - T1) + m * q)"),
        ],
        "loesung": "(m * c * (T2 - T1) + m * q) / 1000",
        "frage": "In einem Schmelzofen sollen {m} kg Aluminium von {T1} °C auf die Schmelztemperatur von {T2} °C gebracht und vollständig geschmolzen werden. Spezifische Wärmekapazität c = {c} kJ/(kg·K), spezifische Schmelzwärme q = {q} kJ/kg. Wie groß ist die insgesamt zuzuführende Wärme Q (in MJ)?",
        "erklaerung": "Der Vorgang besteht aus zwei Abschnitten, die getrennt gerechnet werden müssen: erst Erwärmen bis zur Schmelztemperatur (Q₁ = m · c · Δϑ), dann Schmelzen bei konstanter Temperatur (Q₂ = m · q). Während des Schmelzens steigt die Temperatur nicht – die Energie steckt in der Umwandlung. Wer nur Q₁ rechnet, unterschätzt den Bedarf erheblich.",
        "workedExample": "Gegeben: m = {m} kg, ϑ₁ = {T1} °C, ϑ₂ = {T2} °C, c = {c} kJ/(kg·K), q = {q} kJ/kg\nGesucht: Gesamtwärme Q\nSchritt 1 – Temperaturdifferenz: Δϑ = {T2} − {T1} = {dT} K\nSchritt 2 – Erwärmen: Q₁ = m · c · Δϑ = {m} · {c} · {dT} = {Q1} kJ\nSchritt 3 – Schmelzen: Q₂ = m · q = {m} · {q} = {Q2} kJ\nSchritt 4 – Summe: Q = {Q1} + {Q2} = {Q_kJ} kJ = {loesung} MJ",
    },
    {
        "id": "kx-08",
        "bereich": "auftragsanalyse",
        "kategorie": "Toleranzen & Passungen",
        "einheit": "µm",
        "rundung": 0,
        "toleranz": 0.5,
        "schwierigkeit": 3,
        "variablen": {
            "nenn": {"werte": [25, 30, 40, 50, 60, 80]},
            "ES": {"werte": [21, 25, 30, 39]},
            "es_neg": {"werte": [10, 15, 20, 25]},
            "spanne": {"werte": [15, 20, 25, 30]},
        },
        "original": {"nenn": 40, "ES": 25, "es_neg": 25, "spanne": 25},
        "zwischen": [
            ("ei_neg", "es_neg + spanne"),
            ("hoechst_b", "nenn + ES / 1000"),
            ("mindest_w", "nenn - (es_neg + spanne) / 1000"),
            ("mindestspiel", "es_neg"),
        ],
        "stellen": {"hoechst_b": 3, "mindest_w": 3},
        "loesung": "ES + es_neg + spanne",
        "frage": "Eine Bohrung Ø {nenn} mm hat die Abmaße ES = +{ES} µm und EI = 0 µm, die zugehörige Welle Ø {nenn} mm die Abmaße es = −{es_neg} µm und ei = −{ei_neg} µm. Wie groß ist das Höchstspiel (in µm)?",
        "erklaerung": "Das Höchstspiel entsteht im ungünstigsten Fall: größte Bohrung trifft kleinste Welle. Es gilt also P_max = Höchstmaß Bohrung − Mindestmaß Welle, in Abmaßen ausgedrückt ES − ei. Weil ei negativ ist, werden die Beträge addiert – hier liegt der häufigste Vorzeichenfehler. Das Mindestspiel wäre entsprechend EI − es.",
        "workedExample": "Gegeben: Bohrung Ø{nenn} mit ES = +{ES} µm, EI = 0 µm; Welle Ø{nenn} mit es = −{es_neg} µm, ei = −{ei_neg} µm\nGesucht: Höchstspiel\nSchritt 1 – Höchstmaß der Bohrung: {nenn} + {ES} µm = {hoechst_b} mm\nSchritt 2 – Mindestmaß der Welle: {nenn} − {ei_neg} µm = {mindest_w} mm\nSchritt 3 – Höchstspiel: P_max = ES − ei = {ES} − (−{ei_neg}) = {loesung} µm\nZur Kontrolle: Mindestspiel = EI − es = 0 − (−{es_neg}) = {mindestspiel} µm",
    },
    # ------------------------------------------------------------------
    # Neue Themen: im Bestand bisher gar nicht vertreten.
    # ------------------------------------------------------------------
    {
        "id": "kx-09",
        "bereich": "auftragsanalyse",
        "kategorie": "Maschinenelemente",
        "einheit": "h",
        "rundung": 0,
        "toleranzProzent": 2.0,
        "schwierigkeit": 3,
        "variablen": {
            "C": {"werte": [19.5, 26.0, 33.2, 40.5, 52.0, 63.7]},
            "P": {"von": 3.0, "bis": 15.0, "schritt": 0.5},
            "n": {"werte": [720, 960, 1200, 1450, 1800]},
        },
        "original": {"C": 52.0, "P": 8.5, "n": 1200},
        "zwischen": [
            ("verh", "round(C / P * 10000) / 10000"),
            ("L10", "round((C / P)^3 * 100) / 100"),
            ("umdr", "round(60 * n)"),
        ],
        "loesung": "(C / P)^3 * 1000000 / (60 * n)",
        "frage": "Ein Rillenkugellager mit der dynamischen Tragzahl C = {C} kN wird mit der äquivalenten Belastung P = {P} kN bei n = {n} min⁻¹ betrieben. Welche nominelle Lebensdauer L₁₀ₕ (in Betriebsstunden) ist zu erwarten? (Lebensdauerexponent p = 3)",
        "erklaerung": "Die Grundgleichung L₁₀ = (C/P)^p liefert die Lebensdauer in Millionen Umdrehungen – nicht in Stunden. Erst die Drehzahl macht daraus eine Zeit: L₁₀ₕ = L₁₀ · 10⁶ / (60 · n). Zwei Stolpersteine: der Exponent 3 gilt für Kugellager (bei Rollenlagern 10/3), und die Million darf nicht vergessen werden.",
        "workedExample": "Gegeben: C = {C} kN, P = {P} kN, n = {n} min⁻¹, p = 3\nGesucht: Lebensdauer in Betriebsstunden\nSchritt 1 – Tragzahlverhältnis: C/P = {C} / {P} ≈ {verh}\nSchritt 2 – Lebensdauer in Umdrehungen: L₁₀ = {verh}³ ≈ {L10} Mio. Umdrehungen\nSchritt 3 – Umdrehungen je Stunde: 60 · n = 60 · {n} = {umdr}\nSchritt 4 – Betriebsstunden: L₁₀ₕ = {L10} · 10⁶ / {umdr} ≈ {loesung} h",
    },
    {
        "id": "kx-10",
        "bereich": "auftragsanalyse",
        "kategorie": "Maschinenelemente",
        "einheit": "Schrauben",
        "rundung": 0,
        "toleranz": 0.5,
        "schwierigkeit": 3,
        "variablen": {
            "F_ges": {"von": 60, "bis": 400, "schritt": 20},
            "As": {"werte": [36.6, 58, 84.3, 115, 157]},
            "Rp": {"werte": [640, 900]},
            "ausn": {"werte": [0.7, 0.8, 0.9]},
        },
        "original": {"F_ges": 120, "As": 58, "Rp": 640, "ausn": 0.9},
        "zwischen": [
            ("sig_zul", "round(ausn * Rp * 10) / 10"),
            ("F_V", "round(ausn * Rp * As)"),
            ("F_V_kN", "round(ausn * Rp * As / 100) / 10"),
            ("roh", "round(F_ges * 1000 / (ausn * Rp * As) * 100) / 100"),
        ],
        "loesung": "ceil(F_ges * 1000 / (ausn * Rp * As))",
        "frage": "Eine Flanschverbindung muss eine Vorspannkraft von insgesamt {F_ges} kN aufbringen. Verwendet werden Schrauben mit dem Spannungsquerschnitt Aₛ = {As} mm² und der Streckgrenze Rp0,2 = {Rp} N/mm². Die Streckgrenze darf zu {ausn} ausgenutzt werden. Wie viele Schrauben sind mindestens erforderlich?",
        "erklaerung": "Drei Schritte, und der letzte ist der, an dem es scheitert: Aus zulässiger Spannung und Spannungsquerschnitt folgt die Vorspannkraft je Schraube, daraus die rechnerische Schraubenzahl – und die muss AUFGERUNDET werden. Eine halbe Schraube gibt es nicht, und Abrunden hieße, die geforderte Kraft zu unterschreiten.",
        "workedExample": "Gegeben: F_ges = {F_ges} kN, Aₛ = {As} mm², Rp0,2 = {Rp} N/mm², Ausnutzung {ausn}\nGesucht: Mindestanzahl Schrauben\nSchritt 1 – Zulässige Spannung: σ_zul = {ausn} · {Rp} = {sig_zul} N/mm²\nSchritt 2 – Vorspannkraft je Schraube: F_V = σ_zul · Aₛ = {sig_zul} · {As} ≈ {F_V} N ≈ {F_V_kN} kN\nSchritt 3 – Rechnerische Anzahl: {F_ges} kN / {F_V_kN} kN ≈ {roh}\nSchritt 4 – Aufrunden: {loesung} Schrauben",
    },
    {
        "id": "kx-11",
        "bereich": "auftragsanalyse",
        "kategorie": "Antriebstechnik (mechanisch)",
        "einheit": "mm",
        "rundung": 1,
        "toleranzProzent": 0.5,
        "schwierigkeit": 3,
        "variablen": {
            "d1": {"werte": [80, 100, 112, 125, 140]},
            "d2": {"werte": [250, 280, 315, 355, 400]},
            "e": {"von": 400, "bis": 900, "schritt": 10},
        },
        "original": {"d1": 125, "d2": 400, "e": 630},
        "zwischen": [
            ("t1", "2 * e"),
            ("t2", "round(pi / 2 * (d1 + d2) * 100) / 100"),
            ("t3", "round((d2 - d1)^2 / (4 * e) * 100) / 100"),
            ("i", "round(d2 / d1 * 1000) / 1000"),
        ],
        "loesung": "2 * e + pi / 2 * (d1 + d2) + (d2 - d1)^2 / (4 * e)",
        "frage": "Ein Flachriementrieb hat die Scheibendurchmesser d₁ = {d1} mm und d₂ = {d2} mm bei einem Achsabstand von e = {e} mm. Wie lang muss der Riemen (in mm) sein?",
        "erklaerung": "Die Riemenlänge setzt sich aus drei Teilen zusammen: den beiden geraden Trumen (2 · e), dem Umschlingungsanteil beider Scheiben (π/2 · (d₁ + d₂)) und einem Zuschlag für die Schräglage der Trume ((d₂ − d₁)² / (4e)). Der dritte Summand ist klein, wird aber gern vergessen – bei großen Durchmesserunterschieden fehlen dann schnell mehrere Zentimeter.",
        "workedExample": "Gegeben: d₁ = {d1} mm, d₂ = {d2} mm, e = {e} mm\nGesucht: Riemenlänge L\nSchritt 1 – Gerade Trume: 2 · e = {t1} mm\nSchritt 2 – Umschlingung: π/2 · ({d1} + {d2}) ≈ {t2} mm\nSchritt 3 – Zuschlag: ({d2} − {d1})² / (4 · {e}) ≈ {t3} mm\nSchritt 4 – Summe: L = {t1} + {t2} + {t3} ≈ {loesung} mm\nZur Einordnung: Die Übersetzung beträgt i = d₂/d₁ = {i}.",
    },
    {
        "id": "kx-12",
        "bereich": "auftragsanalyse",
        "kategorie": "Maschinenelemente",
        "einheit": "J",
        "rundung": 2,
        "toleranzProzent": 1.0,
        "schwierigkeit": 3,
        "variablen": {
            "F1": {"von": 50, "bis": 400, "schritt": 10},
            "s1": {"werte": [8, 10, 12, 15, 20]},
            "ds": {"werte": [10, 15, 18, 20, 25]},
        },
        "original": {"F1": 150, "s1": 12, "ds": 18},
        "zwischen": [
            ("R", "round(F1 / s1 * 1000) / 1000"),
            ("s2", "s1 + ds"),
            ("F2", "round(F1 / s1 * (s1 + ds) * 10) / 10"),
            ("W_Nmm", "round(F1 / s1 / 2 * ((s1 + ds)^2 - s1^2))"),
        ],
        "loesung": "F1 / s1 / 2 * ((s1 + ds)^2 - s1^2) / 1000",
        "frage": "Eine Druckfeder wird durch die Kraft F₁ = {F1} N um s₁ = {s1} mm zusammengedrückt. Welche Arbeit W (in J) ist nötig, um sie von {s1} mm weiter auf s₂ = {s2} mm zusammenzudrücken?",
        "erklaerung": "Die Federrate R = F/s ist der Schlüssel – sie steht nicht in der Aufgabe und muss zuerst aus dem gegebenen Wertepaar gebildet werden. Die Arbeit ist die Fläche unter der Federkennlinie zwischen den beiden Wegen: W = R/2 · (s₂² − s₁²). Wer stattdessen R/2 · (s₂ − s₁)² rechnet, unterschlägt die schon gespeicherte Vorspannenergie.",
        "workedExample": "Gegeben: F₁ = {F1} N bei s₁ = {s1} mm, Endweg s₂ = {s2} mm\nGesucht: Zusätzliche Federarbeit W\nSchritt 1 – Federrate: R = F₁ / s₁ = {F1} / {s1} = {R} N/mm\nSchritt 2 – Kraft am Endweg: F₂ = R · s₂ = {R} · {s2} ≈ {F2} N\nSchritt 3 – Arbeit: W = R/2 · (s₂² − s₁²) = {R}/2 · ({s2}² − {s1}²) ≈ {W_Nmm} N·mm\nSchritt 4 – Umrechnung: {W_Nmm} N·mm = {loesung} J",
    },
    {
        "id": "kx-13",
        "bereich": "fertigungstechnik",
        "kategorie": "Fügeverfahren",
        "einheit": "",
        "rundung": 2,
        "toleranzProzent": 1.0,
        "schwierigkeit": 3,
        "variablen": {
            "a": {"werte": [3, 4, 5, 6, 8]},
            "l": {"von": 100, "bis": 400, "schritt": 20},
            "sigma": {"werte": [40, 50, 60, 70, 80]},
            "sig_zul": {"werte": [90, 110, 130, 150]},
        },
        "original": {"a": 5, "l": 180, "sigma": 50, "sig_zul": 110},
        "zwischen": [
            ("F_kN", "round(sigma * 2 * a * l / 1000 * 10) / 10"),
            ("A_w", "2 * a * l"),
            ("sig_vorh", "round(round(sigma * 2 * a * l / 1000 * 10) / 10 * 1000 / (2 * a * l) * 100) / 100"),
        ],
        "loesung": "sig_zul / (round(sigma * 2 * a * l / 1000 * 10) / 10 * 1000 / (2 * a * l))",
        "frage": "Ein Blech ist mit zwei durchgehenden Kehlnähten von je a = {a} mm Nahtdicke und l = {l} mm Länge angeschweißt. Die Verbindung wird mit F = {F_kN} kN auf Zug belastet. Zulässig sind σ_zul = {sig_zul} N/mm². Wie groß ist die vorhandene Sicherheit S?",
        "erklaerung": "Der tragende Querschnitt einer Kehlnaht ist a · l – und weil zwei Nähte vorhanden sind, das Doppelte. Aus Kraft und Fläche folgt die vorhandene Spannung, und erst aus deren Verhältnis zur zulässigen die Sicherheit. Wer die Nahtdicke a mit der Blechdicke verwechselt oder nur eine Naht ansetzt, rechnet um den Faktor 2 daneben.",
        "workedExample": "Gegeben: 2 Kehlnähte mit a = {a} mm, l = {l} mm, F = {F_kN} kN, σ_zul = {sig_zul} N/mm²\nGesucht: Sicherheit S\nSchritt 1 – Tragender Querschnitt: A_w = 2 · a · l = 2 · {a} · {l} = {A_w} mm²\nSchritt 2 – Vorhandene Spannung: σ_vorh = F / A_w = {F_kN} · 1000 / {A_w} ≈ {sig_vorh} N/mm²\nSchritt 3 – Sicherheit: S = σ_zul / σ_vorh = {sig_zul} / {sig_vorh} ≈ {loesung}",
    },
    {
        "id": "kx-14",
        "bereich": "auftragsanalyse",
        "kategorie": "Pneumatik",
        "einheit": "l/min",
        "rundung": 1,
        "toleranzProzent": 1.0,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"werte": [25, 32, 40, 50, 63]},
            "s": {"von": 100, "bis": 500, "schritt": 50},
            "p": {"werte": [4, 5, 6, 7]},
            "takte": {"von": 10, "bis": 40, "schritt": 5},
        },
        "original": {"d": 50, "s": 300, "p": 6, "takte": 25},
        "zwischen": [
            ("A", "round(pi / 4 * d^2 * 100) / 100"),
            ("V_geo", "round(2 * pi / 4 * d^2 * s / 1000000 * 10000) / 10000"),
            ("verd", "p + 1"),
            ("V_norm", "round(2 * pi / 4 * d^2 * s / 1000000 * (p + 1) * 10000) / 10000"),
        ],
        "loesung": "2 * pi / 4 * d^2 * s / 1000000 * (p + 1) * takte",
        "frage": "Ein doppeltwirkender Pneumatikzylinder Ø {d} mm mit {s} mm Hub arbeitet bei einem Betriebsdruck von {p} bar mit {takte} Doppelhüben pro Minute. Die Kolbenstange bleibt unberücksichtigt. Wie groß ist der Luftverbrauch (in Litern angesaugter Luft pro Minute)?",
        "erklaerung": "Der entscheidende Schritt ist der, den man nicht sieht: Der Zylinder verbraucht verdichtete Luft, angegeben wird aber der Bedarf an angesaugter Luft. Das Verdichtungsverhältnis (p + 1)/1 rechnet das um – bei 6 bar Überdruck also der Faktor 7. Wer ihn weglässt, meldet ein Siebtel des tatsächlichen Bedarfs, und der Kompressor ist zu klein.",
        "workedExample": "Gegeben: d = {d} mm, s = {s} mm, p = {p} bar, {takte} Doppelhübe/min\nGesucht: Luftverbrauch in l/min\nSchritt 1 – Kolbenfläche: A = π/4 · {d}² ≈ {A} mm²\nSchritt 2 – Geometrisches Volumen je Doppelhub: V = 2 · A · s ≈ {V_geo} l\nSchritt 3 – Verdichtungsverhältnis: ({p} + 1) / 1 = {verd}\nSchritt 4 – Angesaugte Luft je Doppelhub: {V_geo} · {verd} ≈ {V_norm} l\nSchritt 5 – Je Minute: {V_norm} · {takte} ≈ {loesung} l/min",
    },
    {
        "id": "kx-15",
        "bereich": "fertigungstechnik",
        "kategorie": "Qualitätssicherung",
        "einheit": "",
        "rundung": 2,
        "toleranzProzent": 2.0,
        "schwierigkeit": 3,
        "variablen": {
            "nenn": {"werte": [20, 30, 40, 50]},
            "T": {"werte": [0.05, 0.08, 0.1, 0.15]},
            "abw": {"werte": [0.01, 0.02, 0.03]},
            "s": {"werte": [0.008, 0.01, 0.012, 0.015]},
        },
        "original": {"nenn": 30, "T": 0.05, "abw": 0.02, "s": 0.012},
        "zwischen": [
            ("OSG", "nenn + T"),
            ("USG", "nenn - T"),
            ("xq", "nenn + abw"),
            ("oben", "round((T - abw) * 10000) / 10000"),
            ("unten", "round((T + abw) * 10000) / 10000"),
            ("streu", "round(3 * s * 10000) / 10000"),
        ],
        "stellen": {"OSG": 3, "USG": 3, "xq": 3},
        "loesung": "min(T - abw, T + abw) / (3 * s)",
        "frage": "Ein Maß ist mit {nenn} mm ± {T} mm toleriert. Die Prozessüberwachung ergibt den Mittelwert x̄ = {xq} mm und die Standardabweichung s = {s} mm. Wie groß ist der Prozessfähigkeitsindex cpk?",
        "erklaerung": "cpk misst nicht nur die Streuung, sondern auch die Lage: Maßgeblich ist der KLEINERE Abstand des Mittelwerts zu einer der beiden Grenzen, geteilt durch die halbe Prozessstreubreite (3s). Ein Prozess mit enger Streuung, aber außermittiger Lage bekommt so einen schlechten Wert – zu Recht, denn er läuft auf eine Grenze zu. Der Index cp würde diese Verschiebung übersehen.",
        "workedExample": "Gegeben: {nenn} ± {T} mm, x̄ = {xq} mm, s = {s} mm\nGesucht: cpk\nSchritt 1 – Grenzen: OSG = {OSG} mm, USG = {USG} mm\nSchritt 2 – Abstand nach oben: OSG − x̄ = {OSG} − {xq} = {oben} mm\nSchritt 3 – Abstand nach unten: x̄ − USG = {xq} − {USG} = {unten} mm\nSchritt 4 – Halbe Streubreite: 3 · s = 3 · {s} = {streu} mm\nSchritt 5 – Kleineren Abstand einsetzen: cpk = {oben} / {streu} ≈ {loesung}",
    },
    {
        "id": "kx-16",
        "bereich": "fertigungstechnik",
        "kategorie": "Werkstoffe und Wärmebehandlung",
        "einheit": "°C",
        "rundung": 1,
        "toleranzProzent": 1.0,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"werte": [60, 80, 100, 120, 150]},
            "u": {"werte": [0.05, 0.06, 0.08, 0.1, 0.12]},
            "spiel": {"werte": [0.03, 0.04, 0.05]},
            "alpha_mikro": {"werte": [11.5, 16.5, 23.0]},
            "T0": {"werte": [20]},
        },
        "original": {"d": 120, "u": 0.08, "spiel": 0.05, "alpha_mikro": 11.5, "T0": 20},
        "zwischen": [
            ("gesamt", "round((u + spiel) * 1000) / 1000"),
            ("dT", "round((u + spiel) * 1000000 / (d * alpha_mikro) * 10) / 10"),
        ],
        "stellen": {"gesamt": 3},
        "loesung": "T0 + (u + spiel) * 1000000 / (d * alpha_mikro)",
        "frage": "Eine Nabe soll durch Erwärmen auf eine Welle Ø {d} mm gefügt werden. Das Übermaß beträgt {u} mm, zusätzlich wird ein Fügespiel von {spiel} mm gefordert. Der Wärmeausdehnungskoeffizient der Nabe ist α = {alpha_mikro} · 10⁻⁶ /K, die Raumtemperatur {T0} °C. Auf welche Temperatur (in °C) muss die Nabe erwärmt werden?",
        "erklaerung": "Zu weiten ist nicht nur das Übermaß, sondern auch das Fügespiel – sonst klemmt die Nabe genau in dem Moment, in dem sie sitzen soll, und lässt sich weder aufschieben noch abziehen. Die Aufweitung folgt aus Δd = d · α · ΔT, umgestellt nach ΔT. Und das Ergebnis ist eine Temperaturdifferenz: Die Raumtemperatur muss noch dazu.",
        "workedExample": "Gegeben: d = {d} mm, Übermaß {u} mm, Fügespiel {spiel} mm, α = {alpha_mikro} · 10⁻⁶ /K, ϑ₀ = {T0} °C\nGesucht: Fügetemperatur\nSchritt 1 – Erforderliche Aufweitung: Δd = {u} + {spiel} = {gesamt} mm\nSchritt 2 – Temperaturdifferenz: ΔT = Δd / (d · α) = {gesamt} / ({d} · {alpha_mikro} · 10⁻⁶) ≈ {dT} K\nSchritt 3 – Fügetemperatur: ϑ = ϑ₀ + ΔT = {T0} + {dT} ≈ {loesung} °C",
    },
    {
        "id": "kx-17",
        "bereich": "auftragsanalyse",
        "kategorie": "Instandhaltung",
        "einheit": "%",
        "rundung": 2,
        "toleranzProzent": 0.5,
        "schwierigkeit": 3,
        "variablen": {
            "t": {"von": 1200, "bis": 6000, "schritt": 200},
            "n": {"von": 3, "bis": 12, "schritt": 1},
            "mttr": {"werte": [1.5, 2.0, 2.5, 3.0, 3.5, 4.0]},
        },
        "original": {"t": 2400, "n": 6, "mttr": 3.5},
        "zwischen": [
            ("mtbf", "round(t / n * 100) / 100"),
            ("summe", "round((t / n + mttr) * 100) / 100"),
        ],
        "loesung": "(t / n) / (t / n + mttr) * 100",
        "frage": "Eine Anlage lief {t} Betriebsstunden und fiel in dieser Zeit {n}-mal aus. Die mittlere Reparaturdauer beträgt MTTR = {mttr} h. Wie groß ist die technische Verfügbarkeit (in %)?",
        "erklaerung": "MTBF steht nicht in der Aufgabe – sie ergibt sich erst aus Betriebszeit und Ausfallzahl. Die Verfügbarkeit setzt dann die störungsfreie Zeit ins Verhältnis zur Gesamtzeit aus störungsfreier Zeit und Reparaturzeit. Sie ist deshalb immer kleiner als 100 %, aber nie null – ein häufiger Fehler ist, MTTR im Zähler zu verwenden und damit die Ausfallquote statt der Verfügbarkeit zu erhalten.",
        "workedExample": "Gegeben: Betriebszeit {t} h, {n} Ausfälle, MTTR = {mttr} h\nGesucht: Technische Verfügbarkeit\nSchritt 1 – Mittlere störungsfreie Zeit: MTBF = {t} / {n} = {mtbf} h\nSchritt 2 – Nenner: MTBF + MTTR = {mtbf} + {mttr} = {summe} h\nSchritt 3 – Verfügbarkeit: V = MTBF / (MTBF + MTTR) = {mtbf} / {summe} ≈ {loesung} %",
    },
    {
        "id": "kx-18",
        "bereich": "fertigungstechnik",
        "kategorie": "Wirtschaftliche Fertigung",
        "einheit": "Stück",
        "rundung": 0,
        "toleranz": 0.5,
        "schwierigkeit": 3,
        "variablen": {
            "Kf1": {"von": 2000, "bis": 8000, "schritt": 500},
            "kv1": {"werte": [5.5, 6.0, 6.5, 7.0, 8.0]},
            "dKf": {"von": 2000, "bis": 8000, "schritt": 500},
            "dkv": {"werte": [1.5, 2.0, 2.5, 3.0, 3.3]},
        },
        "original": {"Kf1": 4000, "kv1": 6.5, "dKf": 5500, "dkv": 3.3},
        "zwischen": [
            ("Kf2", "Kf1 + dKf"),
            ("kv2", "round((kv1 - dkv) * 100) / 100"),
            ("roh", "round(dKf / dkv * 100) / 100"),
        ],
        "loesung": "ceil(dKf / dkv)",
        "frage": "Für ein Bauteil stehen zwei Fertigungsverfahren zur Wahl. Verfahren A: Fixkosten {Kf1} €, variable Kosten {kv1} €/Stück. Verfahren B: Fixkosten {Kf2} €, variable Kosten {kv2} €/Stück. Ab welcher Stückzahl ist Verfahren B günstiger?",
        "erklaerung": "Gesucht ist die kritische Menge, bei der beide Verfahren gleich teuer sind: Kf_A + kv_A · x = Kf_B + kv_B · x. Umgestellt ergibt sich x = (Kf_B − Kf_A) / (kv_A − kv_B) – die Differenz der Fixkosten geteilt durch die Ersparnis je Stück. Weil ab dieser Menge B günstiger sein soll, wird aufgerundet: Genau bei der kritischen Menge sind beide noch gleich teuer.",
        "workedExample": "Gegeben: A: {Kf1} € fix + {kv1} €/Stück · B: {Kf2} € fix + {kv2} €/Stück\nGesucht: Kritische Stückzahl\nSchritt 1 – Mehrkosten fix: {Kf2} − {Kf1} = {dKf} €\nSchritt 2 – Ersparnis je Stück: {kv1} − {kv2} = {dkv} €/Stück\nSchritt 3 – Kritische Menge: x = {dKf} / {dkv} ≈ {roh} Stück\nSchritt 4 – Aufrunden: ab {loesung} Stück ist Verfahren B günstiger",
    },
    {
        "id": "kx-19",
        "bereich": "auftragsanalyse",
        "kategorie": "Technisches Zeichnen",
        "einheit": "mm",
        "rundung": 2,
        "toleranzProzent": 0.5,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"von": 20, "bis": 80, "schritt": 5},
            "L": {"von": 40, "bis": 150, "schritt": 10},
            "alpha": {"werte": [1.5, 2, 3, 4, 5]},
        },
        "original": {"d": 40, "L": 90, "alpha": 3},
        "zwischen": [
            ("tanw", "round(tan(alpha) * 100000) / 100000"),
            ("zuwachs", "round(2 * L * tan(alpha) * 1000) / 1000"),
            ("c_kehr", "round(1 / (2 * tan(alpha)) * 100) / 100"),
        ],
        "loesung": "d + 2 * L * tan(alpha)",
        "frage": "Ein Kegel hat den kleinen Durchmesser d = {d} mm und die Kegellänge L = {L} mm. Der Einstellwinkel am Oberschlitten beträgt α/2 = {alpha}°. Wie groß ist der große Kegeldurchmesser D (in mm)?",
        "erklaerung": "Der Einstellwinkel ist der HALBE Kegelwinkel – er beschreibt die Neigung einer Mantellinie zur Achse. Der Radius wächst deshalb um L · tan(α/2), der Durchmesser um das Doppelte. Wer den Faktor 2 vergisst, halbiert die Verjüngung. Zur Probe lässt sich das Kegelverhältnis bilden: C = (D − d)/L.",
        "workedExample": "Gegeben: d = {d} mm, L = {L} mm, α/2 = {alpha}°\nGesucht: Großer Kegeldurchmesser D\nSchritt 1 – Steigung je Seite: tan({alpha}°) ≈ {tanw}\nSchritt 2 – Durchmesserzuwachs: 2 · L · tan(α/2) = 2 · {L} · {tanw} ≈ {zuwachs} mm\nSchritt 3 – Großer Durchmesser: D = {d} + {zuwachs} ≈ {loesung} mm\nProbe: Das Kegelverhältnis beträgt C = 1 : {c_kehr}.",
    },
    {
        "id": "kx-20",
        "bereich": "auftragsanalyse",
        "kategorie": "Werkstoffkunde",
        "einheit": "",
        "rundung": 2,
        "toleranzProzent": 1.0,
        "schwierigkeit": 3,
        "variablen": {
            "d": {"werte": [10, 12, 16, 20, 25]},
            "sigma": {"werte": [120, 150, 180, 200, 220]},
            "Rp": {"werte": [235, 275, 355, 470]},
        },
        "original": {"d": 16, "sigma": 200, "Rp": 355},
        "zwischen": [
            ("A", "round(pi / 4 * d^2 * 100) / 100"),
            ("F_kN", "round(sigma * pi / 4 * d^2 / 1000 * 10) / 10"),
            ("sig_vorh", "round(round(sigma * pi / 4 * d^2 / 1000 * 10) / 10 * 1000 / (pi / 4 * d^2) * 100) / 100"),
        ],
        "loesung": "Rp / (round(sigma * pi / 4 * d^2 / 1000 * 10) / 10 * 1000 / (pi / 4 * d^2))",
        "frage": "Ein Rundstab mit Ø {d} mm wird mit F = {F_kN} kN auf Zug belastet. Die Streckgrenze des Werkstoffs beträgt Rp0,2 = {Rp} N/mm². Wie groß ist die Sicherheit S gegen bleibende Verformung?",
        "erklaerung": "Der Querschnitt steht nicht in der Aufgabe – er muss aus dem Durchmesser gebildet werden, und zwar mit π/4 · d², nicht mit π · d². Danach folgt die vorhandene Spannung aus Kraft durch Fläche, und die Sicherheit als Verhältnis von zulässiger zu vorhandener Spannung. Achtung bei den Einheiten: kN und mm² ergeben erst nach Umrechnung N/mm².",
        "workedExample": "Gegeben: d = {d} mm, F = {F_kN} kN, Rp0,2 = {Rp} N/mm²\nGesucht: Sicherheit gegen bleibende Verformung\nSchritt 1 – Querschnitt: A = π/4 · {d}² ≈ {A} mm²\nSchritt 2 – Vorhandene Spannung: σ = F / A = {F_kN} · 1000 / {A} ≈ {sig_vorh} N/mm²\nSchritt 3 – Sicherheit: S = Rp0,2 / σ = {Rp} / {sig_vorh} ≈ {loesung}",
    },
]
